import type {
  AdminApiController,
} from "../api/admin/controller";
import type {
  AdminMember,
  AdminSessionState,
  BorichResult,
  ChoiceDistribution,
  CreateQuestionCommand,
  CreateSectionCommand,
  CreateSurveyCommand,
  FilterOptions,
  GroupCompareResult,
  HeatmapPoint,
  ImageTagAnswer,
  IdentityResponse,
  LocusPoint,
  PreviewSurvey,
  PreviewSurveyCommand,
  PriorityIssue,
  QuestionSetImportCommand,
  QuestionSetImportPreview,
  QuestionSetImportPreviewCommand,
  QuestionSetImportResult,
  PublishValidationResult,
  Question,
  QuestionSummary,
  ReportNarrativeResult,
  ResponseSummary,
  SectionSummary,
  Survey,
  SurveyAsset,
  SurveyCollaborator,
  SurveyDetail,
  SurveySection,
  TextAnswer,
  TextGroup,
  UpdateQuestionCommand,
  UpdateSectionCommand,
  UpdateSurveyCommand,
} from "../api/admin/model";

export const fakeAdminMember: AdminMember = {
  id: "admin-member-1",
  userId: "user-1",
  email: "admin@example.com",
  role: "super_admin",
  isActive: true,
  createdAt: "2026-05-28T00:00:00.000Z",
};

export const fakePendingAdminMember: AdminMember = {
  id: "admin-member-pending",
  userId: "user-pending",
  email: "pending@example.com",
  role: "admin",
  isActive: false,
  createdAt: "2026-05-28T01:00:00.000Z",
};

export const fakeActiveAdminMember: AdminMember = {
  id: "admin-member-active",
  userId: "user-active",
  email: "member@example.com",
  role: "admin",
  isActive: true,
  createdAt: "2026-05-28T02:00:00.000Z",
};

export const activeAdminSession: AdminSessionState = {
  isAuthenticated: true,
  email: fakeAdminMember.email,
  admin: fakeAdminMember,
  hasSurveyAccess: true,
};

export const pendingAdminSession: AdminSessionState = {
  isAuthenticated: true,
  email: fakePendingAdminMember.email,
  pendingAdmin: fakePendingAdminMember,
};

export const unauthenticatedSession: AdminSessionState = {
  isAuthenticated: false,
};

export const nonMemberSession: AdminSessionState = {
  isAuthenticated: true,
  email: "external.admin@example.com",
};

export const sharedSurveySession: AdminSessionState = {
  isAuthenticated: true,
  email: "viewer@example.com",
  hasSurveyAccess: true,
};

export const fakeSurvey: Survey = {
  id: "survey-1",
  title: { ko: "생활관 만족도 조사", en: "Dormitory Satisfaction Survey" },
  description: { ko: "2026 봄학기" },
  status: "draft",
  publicSlug: undefined,
  publicCode: "8K2PQA",
  versionGroupId: "version-group-1",
  versionNumber: 1,
  parentSurveyId: undefined,
  isLatestVersion: true,
  settings: {},
  createdBy: "user-1",
  startsAt: undefined,
  endsAt: undefined,
  publishedAt: undefined,
  closedAt: undefined,
  createdAt: "2026-05-28T00:00:00.000Z",
  updatedAt: "2026-05-28T00:00:00.000Z",
  accessRole: "owner",
};

export const fakeSurveyCollaborator: SurveyCollaborator = {
  id: "survey-collaborator-1",
  surveyId: "survey-1",
  email: "viewer@example.com",
  role: "viewer",
  invitedBy: "user-1",
  createdAt: "2026-05-28T00:00:00.000Z",
  updatedAt: "2026-05-28T00:00:00.000Z",
};

const emptyFilterOptions: FilterOptions = {
  genders: [],
  semesterGroups: [],
  departments: [],
  rcs: [],
  dormitories: [],
  roomTypes: [],
  dormExperiences: [],
};

export const emptyResponseSummary: ResponseSummary = {
  totalResponses: 0,
  submittedResponses: 0,
  filteredResponses: 0,
  lowSampleThreshold: 10,
  isLowSample: false,
  profileDistribution: {
    gender: [],
    semesterGroup: [],
    department: [],
    rc: [],
    dormitory: [],
    roomType: [],
    dormExperience: [],
  },
  lowSampleGroups: [],
};

export function createFakeAdminApiController(overrides: Partial<AdminApiController> = {}): AdminApiController {
  const controller: AdminApiController = {
    getAdminSessionState: async () => activeAdminSession,
    getCurrentAdmin: async () => fakeAdminMember,
    requestAdminAccess: async () => fakePendingAdminMember,
    listPendingAdminMembers: async () => [fakePendingAdminMember],
    listActiveAdminMembers: async () => [fakeAdminMember, fakeActiveAdminMember],
    approveAdminMember: async (command) => ({
      ...fakePendingAdminMember,
      id: command.memberId,
      role: command.role,
      isActive: true,
    }),
    updateAdminMemberRole: async (command) => ({
      ...fakeActiveAdminMember,
      id: command.memberId,
      role: command.role,
    }),
    deleteAdminMember: async () => undefined,
    signInWithGoogle: async () => undefined,
    signOut: async () => undefined,
    listSurveys: async () => [],
    getSurveyDetail: async (surveyId: string): Promise<SurveyDetail> => ({
      survey: { ...fakeSurvey, id: surveyId },
      sections: [],
      questions: [],
      assets: [],
    }),
    createSurvey: async (command: CreateSurveyCommand) => ({
      ...fakeSurvey,
      title: command.title,
      description: command.description,
    }),
    updateSurvey: async (command: UpdateSurveyCommand) => ({
      ...fakeSurvey,
      id: command.surveyId,
      title: command.title ?? fakeSurvey.title,
      description: command.description ?? fakeSurvey.description,
      settings: command.settings ?? fakeSurvey.settings,
    }),
    archiveSurvey: async (surveyId: string) => ({ ...fakeSurvey, id: surveyId, status: "archived" }),
    deleteSurvey: async () => undefined,
    deleteDraftSurvey: async () => undefined,
    listSurveyCollaborators: async () => [fakeSurveyCollaborator],
    inviteSurveyCollaborator: async (command) => ({
      ...fakeSurveyCollaborator,
      surveyId: command.surveyId,
      email: command.email,
      role: command.role,
    }),
    updateSurveyCollaboratorRole: async (command) => ({
      ...fakeSurveyCollaborator,
      id: command.collaboratorId,
      surveyId: command.surveyId,
      role: command.role,
    }),
    revokeSurveyCollaborator: async (command) => ({
      ...fakeSurveyCollaborator,
      id: command.collaboratorId,
      surveyId: command.surveyId,
      revokedAt: "2026-05-28T03:00:00.000Z",
    }),
    createSection: async (command: CreateSectionCommand): Promise<SurveySection> => ({
      id: "section-1",
      surveyId: command.surveyId,
      sectionKey: command.sectionKey,
      title: command.title,
      description: command.description,
      orderIndex: command.orderIndex,
      sectionType: command.sectionType ?? "general",
      settings: command.settings ?? {},
    }),
    updateSection: async (command: UpdateSectionCommand): Promise<SurveySection> => ({
      id: command.sectionId,
      surveyId: "survey-1",
      sectionKey: "section",
      title: command.title ?? { ko: "섹션" },
      description: command.description,
      orderIndex: command.orderIndex ?? 0,
      sectionType: command.sectionType ?? "general",
      settings: command.settings ?? {},
    }),
    reorderSections: async () => [],
    deleteSection: async () => undefined,
    createQuestion: async (command: CreateQuestionCommand): Promise<Question> => ({
      id: "question-1",
      surveyId: command.surveyId,
      sectionId: command.sectionId,
      questionKey: command.questionKey,
      questionType: command.questionType,
      title: command.title,
      description: command.description,
      orderIndex: command.orderIndex,
      isRequired: command.isRequired ?? true,
      metricType: command.metricType ?? "none",
      topicKey: command.topicKey,
      spaceKey: command.spaceKey,
      config: command.config ?? {},
      validation: command.validation ?? {},
    }),
    updateQuestion: async (command: UpdateQuestionCommand): Promise<Question> => ({
      id: command.questionId,
      surveyId: "survey-1",
      sectionId: "section-1",
      questionKey: "question",
      questionType: command.questionType ?? "text",
      title: command.title ?? { ko: "질문" },
      description: command.description,
      orderIndex: command.orderIndex ?? 0,
      isRequired: command.isRequired ?? true,
      metricType: command.metricType ?? "none",
      topicKey: command.topicKey,
      spaceKey: command.spaceKey,
      config: command.config ?? {},
      validation: command.validation ?? {},
    }),
    reorderQuestions: async () => [],
    deleteQuestion: async () => undefined,
    uploadSurveyImage: async (): Promise<SurveyAsset> => ({
      id: "asset-1",
      surveyId: "survey-1",
      assetType: "image",
      storageBucket: "survey-assets",
      storagePath: "survey-1/image.png",
      metadata: {},
      createdAt: "2026-05-28T00:00:00.000Z",
    }),
    validateBeforePublish: async (): Promise<PublishValidationResult> => ({ canPublish: true, issues: [] }),
    publishSurvey: async () => ({ ...fakeSurvey, status: "published" }),
    closeSurvey: async () => ({ ...fakeSurvey, status: "closed" }),
    createNextVersion: async () => ({ ...fakeSurvey, id: "survey-2", versionNumber: 2 }),
    getPreviewSurvey: async (command: PreviewSurveyCommand): Promise<PreviewSurvey> => ({
      survey: { ...fakeSurvey, id: command.surveyId },
      sections: [],
      questions: [],
      assets: [],
      previewMode: true,
      options: command.options,
    }),
    previewQuestionSetImport: async (command: QuestionSetImportPreviewCommand): Promise<QuestionSetImportPreview> => ({
      templateId: command.templateId,
      title: "2026년도 1학기 생활관 정기 설문조사 질문 목록",
      sections: [],
      questions: [],
      totalSectionCount: 7,
      totalQuestionCount: 207,
      importableSectionCount: 7,
      importableQuestionCount: 207,
      skippedQuestionCount: 0,
    }),
    importQuestionSet: async (command: QuestionSetImportCommand): Promise<QuestionSetImportResult> => ({
      templateId: command.templateId,
      sectionsCreated: 7,
      questionsCreated: 207,
      questionsSkipped: 0,
      sectionKeys: [],
      questionKeys: [],
    }),
    getFilterOptions: async () => emptyFilterOptions,
    getResponseSummary: async (): Promise<ResponseSummary> => emptyResponseSummary,
    getSectionSatisfactionSummary: async (): Promise<SectionSummary[]> => [],
    getQuestionSatisfactionSummary: async (): Promise<QuestionSummary[]> => [],
    getChoiceDistribution: async (): Promise<ChoiceDistribution[]> => [],
    getGroupCompareSummary: async (): Promise<GroupCompareResult[]> => [],
    getPriorityTop5: async (): Promise<PriorityIssue[]> => [],
    getBorichSummary: async (): Promise<BorichResult[]> => [],
    getLocusSummary: async (): Promise<LocusPoint[]> => [],
    getHeatmapPoints: async (): Promise<HeatmapPoint[]> => [],
    listImageTagAnswers: async () => ({ items: [] as ImageTagAnswer[] }),
    listIdentityResponses: async () => ({ items: [] as IdentityResponse[] }),
    getTextGroups: async (): Promise<TextGroup[]> => [],
    listTextAnswers: async () => ({ items: [] as TextAnswer[] }),
    generateReportNarrative: async (command): Promise<ReportNarrativeResult> => ({
      generatedAt: "2026-06-05T00:00:00.000Z",
      blocks: command.blocks.map((block) => ({
        blockId: block.id,
        summary: `${block.title} AI 요약입니다.`,
        body: [`${block.title} 데이터를 바탕으로 보고서 본문을 확장합니다.`],
        evidenceIds: block.evidence.slice(0, 2).map((evidence) => evidence.id),
        caution: block.isLowSample ? "N이 낮아 방향성 참고용으로 해석해야 합니다." : undefined,
        suggestedActions: [`${block.title} 후속 확인`],
      })),
    }),
  };

  return { ...controller, ...overrides };
}
